spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tg-game-miniprogram
    username: root
    password: 123456

  #  redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  #上传下载文件大小
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#日志级别的设置
#logging:
#  level:
#    root: error
#    com:
#      example:
#        youxihoutai: trace
#日志存储路径的设置
#logging:
#  file:
#    path: D:\\_A_GL\\program\\log
#日志文件文件名的设置
#logging:
#  file:
#    name: springboot.log

#mybatis:
#  mapper-locations: classpath:mapper/**Mapper.xml
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto #使用数据库默认id自增策略
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL打印（就是每次操作数据库都会在控制台打印出来SQL语句，建议使用熟练以后注掉此行，不然日志很多）

springdoc:
  api-docs:
    path: /api-docs

pagehelper:
  helper-dialect: mysql
  pageSizeZero: true
  params: count=countSql
  reasonable: true  #当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  support-methods-arguments: true
server:
  port: 8081

